/**
 * @file KernelSection.h
 * @brief Kernel object-model class records emitted into the image section.
 * @ingroup Core
 */
#pragma once

#include "Sora/Core/Traits/TypeTraits.h"
#include "Sora/Core/Traits/MetaInfoList.h"
#include "Sora/Kernel/Core/ClassTypes.h"
#include "Sora/Kernel/Core/Registry.h"

#include <algorithm>
#include <array>
#include <cstdint>
#include <iterator>
#include <unordered_set>
#include <meta>
#include <ranges>
#include <vector>

#if defined(_WIN32)
#    pragma section("kernel$a", read)
#    pragma section("kernel$m", read)
#    pragma section("kernel$z", read)
#    define SORA_KERNEL_SECTION_STORAGE __declspec(allocate("kernel$m")) __attribute__((used))
#elif defined(__APPLE__)
#    define SORA_KERNEL_SECTION_STORAGE __attribute__((used, section("__DATA_CONST,kernel")))
#else
#    define SORA_KERNEL_SECTION_STORAGE __attribute__((used, section("kernel")))
#endif

namespace Sora::Kernel {

    namespace $ {

        /** @brief Adds one interface, implementation, or extension class to a kernel manifest enum. */
        struct KernelClass {
            std::meta::info type{};
        };

        /** @brief Adds every interface, implementation, or extension class visible under one namespace. */
        struct Namespace {
            std::meta::info scope{};
        };

        /** @brief Excludes one interface, implementation, or extension class from a manifest or namespace scan. */
        struct Exclude {
            std::meta::info type{};
        };

    } // namespace $

    namespace Meta {

        consteval bool IsKernelClass(std::meta::info info) {
            return Meta::IsComClass(info) && !IsTie(Meta::RoleOf(info));
        }

    } // namespace Meta

    using KernelClassRegisterFn = void (*)();

    /** @brief Compile-time kernel class manifest expressed with reflection values. */
    struct KernelManifest {
        Sora::Meta::InfoList classes{}; /**< Explicit interface, implementation, or extension classes. */
        /** @brief Namespaces scanned for interface, implementation, or extension classes. */
        Sora::Meta::InfoList namespaces{};
        Sora::Meta::InfoList exclude{}; /**< Classes removed after explicit and namespace collection. */
    };

    /** @brief One object-model class registration thunk stored in a kernel section block. */
    struct KernelSectionRecord {
        Iid classIid{};                        /**< Object-model class identifier. */
        TypeOfClass role{};                    /**< Object-model role. */
        KernelClassRegisterFn registerClass{}; /**< Registers the class node and its declaration edges. */
    };

    /** @brief Common header at the beginning of every kernel section block. */
    struct KernelSectionBlockHeader {
        uint32_t magic{0x4b534f53u}; /**< "SOSK" little-endian marker. */
        uint16_t version{1};
        uint16_t headerSize{sizeof(KernelSectionBlockHeader)};
        uint32_t byteSize{};
        uint32_t count{};
    };

    /** @brief Fixed-size kernel class section block generated by reflection. */
    template<size_t N>
    struct KernelSectionBlock {
        KernelSectionBlockHeader header{
            .byteSize = static_cast<uint32_t>(sizeof(KernelSectionBlock)),
            .count = static_cast<uint32_t>(N),
        };
        std::array<KernelSectionRecord, N> records{};
    };

    /**
     * @brief Build a kernel section block from a reflected enum manifest.
     * @param[in] enumType Reflected enum whose annotations are scanned for kernel class and namespace annotations.
     * @return Kernel section block containing one record for each implementation or extension class.
     */
    consteval KernelManifest KernelManifestFromEnum(std::meta::info enumType) {
        std::vector<std::meta::info> classes;
        std::vector<std::meta::info> namespaces;
        std::vector<std::meta::info> exclude;

        for (auto& enumerator : std::meta::enumerators_of(enumType)) {
            for (std::meta::info annotation : Sora::Meta::AnnotationsOf(enumerator)) {
                const std::meta::info annotationType = Sora::Meta::TypeOf(annotation);
                if (annotationType == ^^$::KernelClass) {
                    auto type = std::meta::dealias(std::meta::extract<$::KernelClass>(annotation).type);
                    if (!std::meta::is_class_type(type) || !Sora::Kernel::Meta::IsKernelClass(type)) {
                        throw std::define_static_string(
                            "Sora kernel manifest included explicit classes must be interface, "
                            "implementation, or extension classes.");
                    }

                    if (!std::ranges::contains(classes, type)) {
                        classes.push_back(type);
                    }
                } else if (annotationType == ^^$::Namespace) {
                    auto scope = std::meta::extract<$::Namespace>(annotation).scope;
                    if (!std::meta::is_namespace(scope)) {
                        throw std::define_static_string("Sora kernel manifest namespaces must be namespaces.");
                    }

                    if (!std::ranges::contains(namespaces, std::meta::dealias(scope))) {
                        namespaces.push_back(std::meta::dealias(scope));
                    }
                } else if (annotationType == ^^$::Exclude) {
                    auto type = std::meta::dealias(std::meta::extract<$::Exclude>(annotation).type);
                    if (!std::meta::is_class_type(type) || !Sora::Kernel::Meta::IsKernelClass(type)) {
                        throw std::define_static_string(
                            "Sora kernel manifest excluded explicit classes must be interface, "
                            "implementation, or extension classes.");
                    }
                    if (!std::ranges::contains(exclude, type)) {
                        exclude.push_back(type);
                    }
                }
            }
        }

        return KernelManifest{
            .classes = Sora::Meta::StaticInfoList(classes),
            .namespaces = Sora::Meta::StaticInfoList(namespaces),
            .exclude = Sora::Meta::StaticInfoList(exclude),
        };
    }

    /**
     * @brief Return a reflected TypeList of all object-model classes in a kernel manifest.
     * @param[in] manifest Kernel manifest whose classes are requested.
     * @return Reflected TypeList of all interface, implementation, and extension classes in @p manifest.
     */
    consteval std::meta::info KernelClassTypeListInfoOf(KernelManifest manifest) {
        std::vector<std::meta::info> classes;

        const auto accepted = [&](std::meta::info type) {
            return !std::ranges::contains(manifest.exclude | std::views::transform(std::meta::dealias), type) &&
                   !std::ranges::contains(classes, type);
        };

        classes.append_range(manifest.classes | std::views::filter([&manifest, &classes](auto&& type) {
                                 return !std::ranges::contains(manifest.exclude, type) &&
                                        !std::ranges::contains(classes, type);
                             }));

        for (std::meta::info ns : manifest.namespaces) {
            classes.append_range(Sora::Meta::MembersOf(ns) | std::views::transform(std::meta::dealias) |
                                 std::views::filter([&classes](auto&& type) {
                                     return Sora::Kernel::Meta::IsKernelClass(type) &&
                                            !std::ranges::contains(classes, type);
                                 }));
        }

        return std::meta::substitute(^^Sora::Traits::TypeList, classes);
    }

    /** @brief Return a reflected TypeList of all object-model classes visible as direct members of @p Scope. */
    template<std::meta::info Scope>
    consteval std::meta::info KernelClassTypeListInfoOf() {
        std::vector<std::meta::info> classes;

        template for (constexpr auto member : Sora::Meta::MembersOf(Scope)) {
            if constexpr (std::meta::is_type(member)) {
                constexpr std::meta::info type = std::meta::dealias(member);
                if constexpr (Meta::IsComClass(type)) {
                    constexpr TypeOfClass role = Meta::RoleOf(type);
                    if constexpr (IsInterface(role) || IsComponent(role)) {
                        classes.push_back(type);
                    }
                }
            }
        }

        return std::meta::substitute(^^Sora::Traits::TypeList, classes);
    }

    template<const KernelManifest& Manifest>
    consteval void ValidateKernelManifest() {
        using Classes = Sora::Meta::InfoType<KernelClassTypeListInfoOf(Manifest)>;
        if constexpr (Classes::size == 0) {
            throw std::define_static_string("Sora kernel manifest contains no implementation or extension classes.");
        }
    }

    template<typename List>
    struct KernelSectionBuilder;

    template<Concept::ComClass... Classes>
        requires((IsInterface(Traits::RoleOf<Classes>) || IsComponent(Traits::RoleOf<Classes>)) && ...)
    struct KernelSectionBuilder<Sora::Traits::TypeList<Classes...>> {
        static consteval auto Build() {
            KernelSectionBlock<sizeof...(Classes)> block{};
            size_t index = 0;
            ((block.records[index++] =
                  KernelSectionRecord{
                      .classIid = Traits::IidOf<Classes>,
                      .role = Traits::RoleOf<Classes>,
                      .registerClass = &RegisterKernelClass<Classes>,
                  }),
             ...);
            return block;
        }
    };

    /** @brief Build a kernel section block for an explicit class batch. */
    template<Concept::ComClass... Classes>
        requires((IsInterface(Traits::RoleOf<Classes>) || IsComponent(Traits::RoleOf<Classes>)) && ...)
    consteval auto BuildKernelSectionBlock() {
        if constexpr (sizeof...(Classes) == 0) {
            throw std::define_static_string(
                "Sora kernel section contains no interface, implementation, or extension class.");
        }
        return KernelSectionBuilder<Sora::Traits::TypeList<Classes...>>::Build();
    }

    /** @brief Build a kernel section block for all visible object-model classes in @p Scope. */
    template<std::meta::info Scope>
    consteval auto BuildKernelSectionBlock() {
        return KernelSectionBuilder<Sora::Meta::InfoType<KernelClassTypeListInfoOf<Scope>()>>::Build();
    }

    /** @brief Build a kernel section block from a reflection manifest. */
    template<const KernelManifest& Manifest>
    consteval auto BuildKernelSectionBlock() {
        using Classes = Sora::Meta::InfoType<KernelClassTypeListInfoOf(Manifest)>;
        if constexpr (Classes::size == 0) {
            throw std::define_static_string("Sora kernel manifest contains no implementation or extension classes.");
        }
        return KernelSectionBuilder<Classes>::Build();
    }

    /** @brief Section emitter whose static anchor is linked into the kernel section. */
    template<const KernelManifest& Manifest>
    struct KernelSection {
        inline static constexpr auto block = BuildKernelSectionBlock<Manifest>();
        [[maybe_unused]] SORA_KERNEL_SECTION_STORAGE inline static constinit const KernelSectionBlockHeader* const
            anchor = &block.header;
    };

    /** @brief Section emitter backed by an enum annotated with kernel manifest annotations. */
    template<std::meta::info Enum>
    struct KernelSectionFromEnum {
        inline static constexpr auto manifest = KernelManifestFromEnum(Enum);
        inline static constexpr auto block = BuildKernelSectionBlock<manifest>();
        [[maybe_unused]] SORA_KERNEL_SECTION_STORAGE inline static constinit const KernelSectionBlockHeader* const
            anchor = &block.header;
    };

    /** @brief Register one kernel section block into the current runtime. */
    void RegisterKernelSectionBlock(const KernelSectionBlockHeader* header);

    /** @brief Register every kernel section block linked into the current image. */
    void EnsureKernelSectionsRegistered();

} // namespace Sora::Kernel
