/**
 * @file ProviderSection.h
 * @brief Provider registration records emitted into the kernel image section.
 * @ingroup Core
 */
#pragma once

#include "Sora/Core/FixedString.h"
#include "Sora/Core/Traits/MetaInfoList.h"
#include "Sora/Kernel/Core/Registry.h"

#include <array>
#include <cstdint>
#include <meta>
#include <vector>

#if defined(_WIN32)
#    pragma section("kernel$a", read)
#    pragma section("kernel$m", read)
#    pragma section("kernel$z", read)
#    define SORA_KERNEL_PROVIDER_SECTION __declspec(allocate("kernel$m")) __attribute__((used))
#elif defined(__APPLE__)
#    define SORA_KERNEL_PROVIDER_SECTION __attribute__((used, section("__DATA_CONST,kernel")))
#else
#    define SORA_KERNEL_PROVIDER_SECTION __attribute__((used, section("kernel")))
#endif

namespace Sora::Kernel {

    using ProviderRegisterFn = void (*)();

    namespace $ {

        /** @brief Adds one provider class to a provider manifest enum. */
        struct Provider {
            std::meta::info type{};
        };

        /** @brief Adds every provider class visible under one namespace to a provider manifest enum. */
        struct Namespace {
            std::meta::info scope{};
        };

        /** @brief Excludes one provider class from a provider manifest enum or namespace scan. */
        struct Exclude {
            std::meta::info type{};
        };

    } // namespace $

    /** @brief Compile-time provider manifest expressed with reflection values. */
    struct ProviderManifest {
        Sora::Meta::InfoList types{};      /**< Explicit provider classes. */
        Sora::Meta::InfoList namespaces{}; /**< Namespaces scanned for provider classes. */
        Sora::Meta::InfoList exclude{};    /**< Provider classes removed after explicit and namespace collection. */
    };

    /** @brief One provider registration thunk stored in a kernel section block. */
    struct ProviderSectionRecord {
        Iid providerIid{};                     /**< Provider class identifier. */
        TypeOfClass role{};                    /**< Provider object-model role. */
        ProviderRegisterFn registerProvider{}; /**< Registers this provider into runtime metaclasses. */
    };

    /** @brief Common header at the beginning of every provider section block. */
    struct ProviderSectionBlockHeader {
        uint32_t magic{0x4b505253u}; /**< "SRPK" little-endian marker. */
        uint16_t version{1};
        uint16_t headerSize{sizeof(ProviderSectionBlockHeader)};
        uint32_t byteSize{};
        uint32_t count{};
    };

    /** @brief Fixed-size provider section block generated by reflection. */
    template<size_t N>
    struct ProviderSectionBlock {
        ProviderSectionBlockHeader header{
            .byteSize = static_cast<uint32_t>(sizeof(ProviderSectionBlock)),
            .count = static_cast<uint32_t>(N),
        };
        std::array<ProviderSectionRecord, N> records{};
    };

    template<Concept::ComponentClass Provider>
    void RegisterProviderThunk() {
        RegisterObjectProviders<Provider>();
    }

    consteval TypeOfClass RoleOf(std::meta::info type) {
        type = std::meta::dealias(type);
        if (type == ^^BaseUnknown) {
            return TypeOfClass::BaseUnknown;
        }

        auto result = Sora::$::GetSingleOptional<Sora::Kernel::$::Role>(type);
        return result ? result->type : TypeOfClass::NothingType;
    }

    consteval bool ImplementsAnyInterface(std::meta::info type) {
        for (const auto& annotation : std::meta::annotations_of(std::meta::dealias(type))) {
            auto annotationType = std::meta::type_of(annotation);
            if (Sora::Meta::IsSpecializationOf<Sora::Kernel::$::Implements>(annotationType)) {
                return !std::meta::template_arguments_of(annotationType).empty();
            }
        }
        return false;
    }

    consteval bool IsSectionProvider(std::meta::info type) {
        if (!std::meta::is_class_type(type)) {
            return false;
        }
        const TypeOfClass role = RoleOf(type);
        return IsComponent(role) && ImplementsAnyInterface(type);
    }

    template<typename T>
    consteval bool IsSectionProvider() {
        return IsSectionProvider(std::meta::dealias(^^T));
    }

    consteval bool ContainsInfo(const std::vector<std::meta::info>& items, std::meta::info item) {
        item = std::meta::dealias(item);
        for (std::meta::info current : items) {
            if (std::meta::dealias(current) == item) {
                return true;
            }
        }
        return false;
    }

    consteval bool ContainsInfo(Sora::Meta::InfoList items, std::meta::info item) {
        item = std::meta::dealias(item);
        for (std::meta::info current : items) {
            if (std::meta::dealias(current) == item) {
                return true;
            }
        }
        return false;
    }

    consteval void AddProvider(std::vector<std::meta::info>& providers, std::meta::info type,
                               Sora::Meta::InfoList exclude) {
        type = std::meta::dealias(type);
        if (!IsSectionProvider(type) || ContainsInfo(exclude, type) || ContainsInfo(providers, type)) {
            return;
        }
        providers.push_back(type);
    }

    consteval void AddNamespaceProviders(std::vector<std::meta::info>& providers, std::meta::info scope,
                                         Sora::Meta::InfoList exclude) {
        for (std::meta::info member : std::meta::members_of(scope, std::meta::access_context::unchecked())) {
            if (std::meta::is_type(member)) {
                AddProvider(providers, std::meta::dealias(member), exclude);
            }
        }
    }

    consteval Sora::Meta::InfoList StaticInfoList(std::vector<std::meta::info> items) {
        auto storage = std::define_static_array(items);
        Sora::Meta::InfoList result;
        result.first = storage.data();
        result.count = items.size();
        return result;
    }

    consteval ProviderManifest ProviderManifestFromEnum(std::meta::info enumType) {
        std::vector<std::meta::info> types;
        std::vector<std::meta::info> namespaces;
        std::vector<std::meta::info> exclude;

        for (std::meta::info enumerator : std::meta::enumerators_of(enumType)) {
            for (std::meta::info annotation : std::meta::annotations_of(enumerator)) {
                const std::meta::info annotationType = std::meta::type_of(annotation);
                if (annotationType == ^^$::Provider) {
                    types.push_back(std::meta::extract<$::Provider>(annotation).type);
                } else if (annotationType == ^^$::Namespace) {
                    namespaces.push_back(std::meta::extract<$::Namespace>(annotation).scope);
                } else if (annotationType == ^^$::Exclude) {
                    exclude.push_back(std::meta::extract<$::Exclude>(annotation).type);
                }
            }
        }

        return ProviderManifest{
            .types = StaticInfoList(types),
            .namespaces = StaticInfoList(namespaces),
            .exclude = StaticInfoList(exclude),
        };
    }

    consteval std::meta::info ProviderTypeListInfoOf(ProviderManifest manifest) {
        std::vector<std::meta::info> providers;

        for (std::meta::info type : manifest.types) {
            AddProvider(providers, type, manifest.exclude);
        }
        for (std::meta::info scope : manifest.namespaces) {
            AddNamespaceProviders(providers, scope, manifest.exclude);
        }

        return std::meta::substitute(^^Sora::Traits::TypeList, providers);
    }

    using EmptyProviderTypeList = Sora::Traits::TypeList<>;

    template<const ProviderManifest& Manifest>
    using ProviderTypeListOfManifest = Sora::Meta::InfoType<ProviderTypeListInfoOf(Manifest)>;

    template<const ProviderManifest& Manifest>
    consteval void ValidateProviderManifest() {
        using Providers = ProviderTypeListOfManifest<Manifest>;
        if constexpr (Providers::size == 0) {
            throw std::define_static_string("Sora provider manifest contains no provider classes.");
        }
    }

    /** @brief Return a reflected TypeList of all provider classes visible as direct members of @p Scope. */
    template<std::meta::info Scope>
    consteval std::meta::info ProviderTypeListInfoOf() {
        std::vector<std::meta::info> providers;
        constexpr auto members =
            std::define_static_array(std::meta::members_of(Scope, std::meta::access_context::unchecked()));

        template for (constexpr auto member : members) {
            if constexpr (std::meta::is_type(member)) {
                constexpr auto type = std::meta::dealias(member);
                if constexpr (std::meta::is_class_type(type)) {
                    using T = Sora::Meta::InfoType<type>;
                    if constexpr (IsSectionProvider(^^T)) {
                        providers.push_back(type);
                    }
                }
            }
        }

        return std::meta::substitute(^^Sora::Traits::TypeList, providers);
    }

    template<std::meta::info Scope>
    using ProviderTypeListOf = Sora::Meta::InfoType<ProviderTypeListInfoOf<Scope>()>;

    template<typename List>
    struct ProviderSectionBuilder;

    template<Concept::ComponentClass... Providers>
    struct ProviderSectionBuilder<Sora::Traits::TypeList<Providers...>> {
        static consteval auto Build() {
            ProviderSectionBlock<sizeof...(Providers)> block{};
            size_t index = 0;
            ((block.records[index++] =
                  ProviderSectionRecord{
                      .providerIid = Traits::IidOf<Providers>,
                      .role = Traits::RoleOf<Providers>,
                      .registerProvider = &RegisterProviderThunk<Providers>,
                  }),
             ...);
            return block;
        }
    };

    /** @brief Validate that an explicit provider batch is non-empty. */
    template<Concept::ComponentClass... Providers>
    consteval void ValidateProviderSectionFor() {
        static_assert(sizeof...(Providers) != 0, "Sora provider section batch must contain at least one provider.");
        static_assert((IsSectionProvider<Providers>() && ...),
                      "Every provider section type must implement an interface.");
    }

    /** @brief Build a provider section block for an explicit provider batch. */
    template<Concept::ComponentClass... Providers>
    consteval auto BuildProviderSectionBlockFor() {
        ValidateProviderSectionFor<Providers...>();
        return ProviderSectionBuilder<Sora::Traits::TypeList<Providers...>>::Build();
    }

    /** @brief Validate that @p Scope exposes at least one provider class to the section generator. */
    template<std::meta::info Scope>
    consteval void ValidateProviderSection() {
        using Providers = ProviderTypeListOf<Scope>;
        if constexpr (Providers::size == 0) {
            throw std::define_static_string("Sora provider section contains no visible provider classes.");
        }
    }

    /** @brief Build a provider section block for all visible providers in @p Scope. */
    template<std::meta::info Scope>
    consteval auto BuildProviderSectionBlock() {
        return ProviderSectionBuilder<ProviderTypeListOf<Scope>>::Build();
    }

    /** @brief Build a provider section block from a reflection manifest. */
    template<const ProviderManifest& Manifest>
    consteval auto BuildProviderSectionBlock() {
        ValidateProviderManifest<Manifest>();
        return ProviderSectionBuilder<ProviderTypeListOfManifest<Manifest>>::Build();
    }

    /** @brief Section emitter whose static anchor is linked into the kernel section. */
    template<const ProviderManifest& Manifest>
    struct KernelSection {
        inline static constexpr auto block = BuildProviderSectionBlock<Manifest>();
        [[maybe_unused]] SORA_KERNEL_PROVIDER_SECTION inline static constinit const ProviderSectionBlockHeader* const
            anchor = &block.header;
    };

    /** @brief Section emitter backed by an enum annotated with provider manifest annotations. */
    template<std::meta::info Enum>
    struct KernelSectionFromEnum {
        inline static constexpr auto manifest = ProviderManifestFromEnum(Enum);
        inline static constexpr auto block =
            ProviderSectionBuilder<Sora::Meta::InfoType<ProviderTypeListInfoOf(manifest)>>::Build();
        [[maybe_unused]] SORA_KERNEL_PROVIDER_SECTION inline static constinit const ProviderSectionBlockHeader* const
            anchor = &block.header;
    };

    /** @brief Register one provider section block into the current runtime. */
    void RegisterProviderSectionBlock(const ProviderSectionBlockHeader* header);

    /** @brief Register every provider section block linked into the current image. */
    void EnsureProviderSectionsRegistered();

} // namespace Sora::Kernel

#define SORA_KERNEL_DEFINE_PROVIDER_SECTION(Name, ...)                                                                 \
    namespace {                                                                                                        \
        constexpr auto Name##Block = ::Sora::Kernel::Tie::BuildProviderSectionBlockFor<__VA_ARGS__>();                 \
        [[maybe_unused]] SORA_KERNEL_PROVIDER_SECTION const ::Sora::Kernel::Tie::ProviderSectionBlockHeader* const     \
            Name = &Name##Block.header;                                                                                \
    }

#define SORA_KERNEL_DEFINE_PROVIDER_SECTION_FROM_SCOPE(Name, Scope)                                                    \
    namespace {                                                                                                        \
        constexpr auto Name##Block = ::Sora::Kernel::Tie::BuildProviderSectionBlock<^^Scope>();                        \
        [[maybe_unused]] SORA_KERNEL_PROVIDER_SECTION const ::Sora::Kernel::Tie::ProviderSectionBlockHeader* const     \
            Name = &Name##Block.header;                                                                                \
    }
