/**
 * @file Polymorphism.h
 * @brief Inheritance-free, reflection-driven runtime polymorphism.
 *
 * Provides a "structural duck-type adaptor": given an interface type @p Iface (a class declaring
 * virtual member functions) and an unrelated implementation type @p Impl whose members satisfy those
 * signatures structurally, synthesises at compile time a flat function-pointer vtable @ref Vtable
 * that dispatches into @p Impl, with no inheritance relationship between @p Iface and @p Impl.
 *
 * The vtable layout is generated by @c std::meta::define_aggregate driven by a P2996 reflection scan
 * of @p Iface; each thunk is a non-capturing generic lambda that forwards to the matching method on
 * @p Impl. The resulting cost model is:
 *   - One indirect call per dispatch (identical to a classical virtual call).
 *   - Two pointers per @ref Adaptor (one for the target object, one for the vtable).
 *   - Zero per-instance allocation, zero type-erasure boxing.
 *   - Inlinable thunks: the optimiser sees through the lambda into the target method.
 *
 * The result is the runtime cost of @c virtual without forcing the implementor to inherit from
 * anything; useful for plug-in registration, ABI-stable wrappers around third-party types, gradual
 * refactoring of static-dispatch hierarchies, and concept-style interfaces with runtime polymorphism.
 *
 * @par Method selection
 * Methods on @p Iface participate in the vtable when they are non-static, non-special member
 * functions (constructors and destructors are always excluded). The selection is steered by two
 * annotation tags from @ref Anno:
 *   - @c [[=Skip{}]]  excludes an otherwise eligible method.
 *   - @c [[=Force{}]] includes a non-virtual method that would otherwise be skipped.
 * Pure-virtual methods are always selected unless tagged with @ref Skip.
 *
 * @par Signature compatibility
 * For a selected Iface method @c R Foo(P...) cv, the matching Impl method must have:
 *   - identical identifier,
 *   - identical parameter types (in order),
 *   - identical cv-qualification on the implicit object parameter,
 *   - identical return type.
 * Reference-qualifiers (@c & / @c &&) on the source method have no free-function counterpart and are
 * dropped from the synthesised thunk; users should avoid them on Iface methods. Default arguments
 * on Iface methods are not propagated through the thunk (function pointers do not carry them).
 *
 * @ingroup Core
 */
#pragma once

#include "Sora/Core/ABI.h"
#include "Sora/Core/Hash.h"
#include "Sora/Core/Traits/TypeTraits.h"
#include "Sora/Core/Traits/InheritanceTraits.h"
#include "Sora/Core/Traits/NamingTraits.h"

#include <algorithm>
#include <bit>
#include <cstddef>
#include <format>
#include <meta>
#include <span>
#include <string_view>
#include <vector>

namespace Sora {

    namespace $ {

        struct SkipInPolymorphism {
            constexpr bool operator==(const SkipInPolymorphism&) const = default;
        };

        struct ForceInPolymorphism {
            constexpr bool operator==(const ForceInPolymorphism&) const = default;
        };

        namespace Polymorphism {

            using Skip = Sora::$::SkipInPolymorphism;
            using Force = Sora::$::ForceInPolymorphism;

        } // namespace Polymorphism

    } // namespace $

    namespace Polymorphism {

        namespace $ {

            using Skip = Sora::$::Polymorphism::Skip;
            using Force = Sora::$::Polymorphism::Force;

        } // namespace $

        /** @cond INTERNAL */
        namespace Detail {

            /**
             * @brief @c true if @p m should appear in the vtable per the @ref Anno tag policy.
             *        Default policy: include virtual methods; @ref Skip overrides; @ref Force
             *        promotes non-virtual methods into the vtable.
             */
            consteval bool IsAdapterEntry(std::meta::info m) {
                if (!Sora::Meta::IsRegularMethod(m)) {
                    return false;
                }
                if (Sora::$::Has<$::Skip>(m)) {
                    return false;
                }
                const bool forced = Sora::$::Has<$::Force>(m);
                const bool virt = std::meta::is_virtual(m) || std::meta::is_pure_virtual(m);
                return virt || forced;
            }

            /**
             * @brief Reflected, declaration-ordered list of @p Iface methods participating in the vtable,
             *        walking the entire base-class hierarchy.
             *
             * Override-aware: when a derived interface @c override's a base method (same identifier and
             * signature), only the derived entity is kept. Otherwise inherited base methods are carried
             * through, so a @c Vtable<IDerived,Impl> projects every method @c IDerived's contract
             * implies; direct + inherited.
             *
             * Order: direct members of @c Iface first (declaration order), then base methods in
             * breadth-first hierarchy order.
             */
            template<typename Iface>
            consteval std::vector<std::meta::info> SelectMethods() {
                std::vector<std::meta::info> out;
                Sora::Meta::WalkHierarchyMembers(^^Iface, [&](size_t /*depth*/, std::meta::info m) {
                    if (!IsAdapterEntry(m)) {
                        return;
                    }
                    // Override filter: skip a base-class method whose identifier matches one already
                    // selected from a more-derived class. The first occurrence wins because the walk
                    // is derived-first.
                    for (const auto name = Sora::Meta::IdentifierOf(m); auto kept : out) {
                        if (Sora::Meta::IdentifierOf(kept) == name) {
                            return;
                        }
                    }
                    out.push_back(m);
                });
                return out;
            }

            /**
             * @brief Same as @ref SelectMethods, materialised in static storage so it can drive @c template for.
             */
            template<typename Iface>
            inline constexpr auto kSelectedMethods = std::define_static_array(SelectMethods<Iface>());

            /**
             * @brief Build the cv-qualified @c Impl* matching the cv-qualifiers of member @p m.
             *        Reference-qualifiers are intentionally not propagated (no free-function counterpart).
             *        Throws a compile-time diagnostic naming the offending type if @p impl is not a class.
             */
            consteval std::meta::info ThisPointerType(std::meta::info impl, std::meta::info m) {
                if (!std::meta::is_class_type(impl)) {
                    throw std::define_static_string(
                        std::format("Polymorphism::ThisPointerType: implementation type '{}' is not a class type; "
                                    "only class types can host the synthesised vtable thunks.",
                                    Sora::Meta::DisplayStringOf(impl)));
                }
                auto t = impl;
                if (std::meta::is_const(m)) {
                    t = std::meta::add_const(t);
                }
                if (std::meta::is_volatile(m)) {
                    t = std::meta::add_volatile(t);
                }
                return std::meta::add_pointer(t);
            }

            /**
             * @brief Project a function reflection's parameter list to a list of parameter type infos.
             *        Throws a compile-time diagnostic naming the offending entity if @p f is not callable.
             */
            consteval std::vector<std::meta::info> ParamTypes(std::meta::info f) {
                if (!std::meta::is_function(f)) {
                    throw std::define_static_string(
                        std::format("Polymorphism::ParamTypes: '{}' is not a function reflection; only methods "
                                    "participate in vtable synthesis.",
                                    Sora::Meta::DisplayStringOf(f)));
                }
                std::vector<std::meta::info> out = Sora::Meta::ParamsOf(f) | std::views::transform(std::meta::type_of) |
                                                   std::ranges::to<std::vector>();
                return out;
            }

            /**
             * @brief Build the thunk pointer type @c R(*)(cv Impl*,Args...) for member @p m.
             *        Combines the cv-qualified @c this pointer with the original parameter types into
             *        a flat free-function-pointer signature via @c std::meta::substitute.
             */
            consteval std::meta::info ThunkPointerType(std::meta::info impl, std::meta::info m) {
                std::vector<std::meta::info> args;
                const auto pts = ParamTypes(m);
                args.reserve(pts.size() + 2);
                args.push_back(std::meta::return_type_of(m));
                args.push_back(ThisPointerType(impl, m));
                args.append_range(pts);
                return std::meta::substitute(^^Sora::Traits::FunctionPointer, args);
            }

            /**
             * @brief Aggregate-member specs for @ref Vtable<Iface, Impl>: one slot per selected Iface method.
             *        Slot names are the bare method identifier; @ref Define rejects overload sets so
             *        names are guaranteed unique within the aggregate.
             */
            template<typename Iface, typename Impl>
            consteval std::vector<std::meta::info> VtableSpecs() {
                std::vector<std::meta::info> out;
                for (auto m : SelectMethods<Iface>()) {
                    out.push_back(
                        std::meta::data_member_spec(ThunkPointerType(^^Impl, m), {.name = Meta::IdentifierOf(m)}));
                }
                return out;
            }

            /**
             * @brief Find the Impl method matching the signature of Iface member @p ifaceMember.
             *
             * Strict structural match: identifier, parameter types, cv-qualifiers, and return type all
             * equal. Returns the null reflection (@c std::meta::info{}) when no compatible counterpart
             * exists. Overload sets are resolved by signature; the first matching overload wins.
             * Throws compile-time diagnostics for malformed inputs (non-class @p classType,
             * non-callable @p ifaceMember).
             */
            consteval std::meta::info FindCompatible(std::meta::info classType, std::meta::info ifaceMember) {
                if (!std::meta::is_class_type(classType)) {
                    throw std::define_static_string(
                        std::format("Polymorphism::FindCompatible: implementation argument '{}' is not a class type.",
                                    Sora::Meta::DisplayStringOf(classType)));
                }
                if (!std::meta::is_function(ifaceMember)) {
                    throw std::define_static_string(
                        std::format("Polymorphism::FindCompatible: interface member '{}' is not a callable reflection.",
                                    Sora::Meta::DisplayStringOf(ifaceMember)));
                }
                const auto name = Meta::IdentifierOf(ifaceMember);
                const auto wantRet = std::meta::return_type_of(ifaceMember);
                const auto wantParams = ParamTypes(ifaceMember);
                const bool wantC = std::meta::is_const(ifaceMember), wantV = std::meta::is_volatile(ifaceMember);
                // Walk the impl's full base-class hierarchy in derived-first order so that, when a
                // derived class overrides an inherited base method, we lock onto the derived entity
                // (the dispatch we install in the vtable) rather than silently picking the base.
                std::meta::info match = std::meta::info{};
                Sora::Meta::WalkHierarchyMembers(classType, [&](size_t /*depth*/, std::meta::info m) {
                    if (match != std::meta::info{}) {
                        return;
                    }
                    if (!Sora::Meta::IsRegularMethod(m)) {
                        return;
                    }
                    if (!std::meta::has_identifier(m) || Meta::IdentifierOf(m) != name) {
                        return;
                    }
                    if (std::meta::is_const(m) != wantC || std::meta::is_volatile(m) != wantV) {
                        return;
                    }
                    if (std::meta::return_type_of(m) != wantRet) {
                        return;
                    }
                    if (!std::ranges::equal(ParamTypes(m), wantParams)) {
                        return;
                    }
                    match = m;
                });
                return match;
            }

            /**
             * @brief Compile-time predicate: every selected method of @p Iface has a compatible @p Impl method.
             */
            template<typename Iface, typename Impl>
            consteval bool AllMethodsMatch() {
                return std::ranges::all_of(SelectMethods<Iface>(),
                                           [&](auto m) { return FindCompatible(^^Impl, m) != std::meta::info{}; });
                return true;
            }

            /**
             * @brief Return the first method identifier that occurs more than once among the selected
             *        methods of @p Iface, or an empty view when every selected method has a unique name.
             *
             * @TODO Lift this restriction by mangling overloaded slots with a stable signature suffix
             * (e.g. @c Draw__int_int) and exposing a PMF-keyed @c Adaptor::invoke<Pmf>() accessor that
             * resolves the matching slot via reflection. The current single-pass design rejects
             * overload sets up front to keep slot identifiers (and the user-facing call surface
             * @c vtable().Name) clean while the broader vtable composition is still settling.
             */
            template<typename Iface>
            consteval std::string_view FindOverloadCollision() {
                const auto methods = SelectMethods<Iface>();
                for (size_t i : std::views::iota(size_t{0}, methods.size())) {
                    const auto name = Meta::IdentifierOf(methods[i]);
                    for (size_t j : std::views::iota(i + 1, methods.size())) {
                        if (Meta::IdentifierOf(methods[j]) == name) {
                            return name;
                        }
                    }
                }
                return {};
            }

            /**
             * @brief @c true when no two selected methods of @p Iface share an identifier.
             */
            template<typename Iface>
            consteval bool NoOverloadCollisions() {
                return FindOverloadCollision<Iface>().empty();
            }

        } // namespace Detail
        /** @endcond */

        /**
         * @brief Stable 128-bit hash over the projected vtable shape of @p Iface.
         *
         * Folds every selected method's Itanium-mangled signature into an FNV-1a128 digest. The hash
         * is keyed on @p Iface alone; the choice of @c Impl never participates; and changes whenever
         * any factor that would alter the synthesised vtable shape changes: a method added, removed,
         * renamed, reordered, or whose signature (parameter types, return type, cv-qualifier) shifts.
         *
         * The Itanium ABI mangling captures everything an external observer would care about for
         * binary compatibility, so the digest is suitable as an ABI-compatibility token: persist it
         * alongside a serialised interface contract and a future build's mismatch reveals itself as a
         * digest difference rather than as a corrupted vtable at run time.
         *
         * @tparam Iface Interface type whose selected methods are reflected and mangled.
         */
        template<typename Iface, bool ConsiderName = false>
        consteval uint128_t AbiDigest() {
            // Materialise reflected spelling into constexpr-friendly byte buffers so we can feed FNV-1a's
            // @c std::span<const std::byte> API without reinterpret_cast, which is forbidden in a constant expression.
            Sora::Hashing::Fnv1a128State h;
            template for (constexpr auto m : Detail::kSelectedMethods<Iface>) {
                constexpr std::string_view mangled = ABI::Itanium::Mangle(m);
                auto bytes = Sora::Meta::BytesOf(mangled);
                h.Feed(std::span<const std::byte>{bytes.data(), bytes.size()});
            }
            if constexpr (ConsiderName) {
                constexpr std::string_view name = Sora::Traits::UniqueName<Iface>;
                auto bytes = Sora::Meta::BytesOf(name);
                h.Feed(std::span<const std::byte>{bytes.data(), bytes.size()});
            }
            return h.Finalize();
        }

        /**
         * @brief Aggregate vtable shape for the (Iface, Impl) pair — forward-declared.
         *
         * The shape is *completed* by @ref Define via `std::meta::define_aggregate` once per
         * (Iface, Impl) pair, mirroring the @c Mashiro::SoA::Define pattern. Until completed, the type
         * is incomplete; querying its members or instantiating @ref kVtable triggers a clear diagnostic
         * directing the user to call @ref Define first.
         *
         * @tparam Iface Interface type (declares the methods to be dispatched).
         * @tparam Impl  Implementation type (any class type whose methods structurally match @p Iface).
         */
        template<typename Iface, typename Impl>
        struct Vtable;

        /**
         * @brief Complete the @ref Vtable<Iface, Impl> aggregate via `define_aggregate`.
         *
         * **Must be invoked from a `consteval { }` block at namespace scope, exactly once per
         * (Iface, Impl) pair.** After the call, `Vtable<Iface, Impl>` is a complete aggregate carrying
         * one function-pointer slot per selected Iface method, named after the source method.
         *
         * @par Overload limitation (current)
         * Slot names are the bare method identifier, so the aggregate cannot host two selected methods
         * sharing a name. `Define` rejects overload sets up front with a `static_assert` carrying the
         * colliding identifier; either rename one of the overloads or mark the secondary one with
         * `[[=Anno::Skip{}]]`.
         *
         * @TODO Lift this restriction by mangling overloaded slots with a deterministic signature
         * suffix (e.g. `Draw__int_int`) and exposing a PMF-keyed `Adaptor::invoke<Pmf>()` accessor that
         * resolves the matching slot via reflection. Tracked as a future extension; the rejection is in
         * place to keep the user-facing call surface (`vtable().Name`) clean while the broader vtable
         * composition is still settling.
         *
         * @code
         * consteval { Mashiro::Polymorphism::Define<IDrawable, Square>(); }
         * @endcode
         */
        template<typename Iface, typename Impl>
        consteval void Define() {
            constexpr auto collision = Detail::FindOverloadCollision<Iface>();
            if constexpr (!collision.empty()) {
                throw std::define_static_string(
                    std::format("Polymorphism::Define: interface '{}' has overloaded selected method '{}'. "
                                "The current name-keyed vtable cannot disambiguate overload sets — rename one "
                                "of the overloads or skip it with [[=Anno::Skip{}]]. (Tracked TODO: signature-"
                                "mangled slots + PMF-keyed Adaptor::invoke<Pmf>().)",
                                Sora::Meta::DisplayStringOf(^^Iface), collision));
            }
            std::meta::define_aggregate(^^Vtable<Iface, Impl>, Detail::VtableSpecs<Iface, Impl>());
        }

        /**
         * @brief Concept: @p Impl provides every selected method of @p Iface with a compatible signature
         *        and the interface contains no overloaded selected methods.
         *
         * Compatibility is structural; identical name, parameter types, cv-qualifiers, and return type.
         * The overload-uniqueness clause makes the concept honest: an interface with overloaded methods
         * cannot be projected through the current name-keyed aggregate, so it cannot model @ref Implements
         * until that limitation is lifted (see @ref Define). Failure produces a constraint-
         * failure diagnostic at @ref kVtable / @ref Adaptor request, pointing at the (Iface, Impl) pair.
         */
        template<typename Impl, typename Iface>
        concept Implements = std::is_class_v<Iface> && std::is_class_v<Impl> && Detail::NoOverloadCollisions<Iface>() &&
                             Detail::AllMethodsMatch<Iface, Impl>();

        /** @cond INTERNAL */
        namespace Detail {

            /**
             * @brief Static, non-generic thunk specialised on the Impl method's pointer-to-member-function
             *        plus its concrete signature. Provides a single free-function @c Invoke whose
             *        parameter types are exactly the synthesised vtable-slot signature, allowing decay
             *        to a function pointer without the unary @c + restriction that affects generic
             *        lambdas.
             *
             * Dispatch uses the canonical @c (self->*Pmf)(args...) form. The pointer-to-member-function
             * is carried as a non-type template parameter (@c auto Pmf) so each instantiation has a
             * distinct constant; even when several thunks share @c (Self,R,As...) they remain
             * independent functions with independent code, sidestepping any NTTP-folding hazards.
             *
             * @tparam Self The cv-qualified @p Impl type to bind as the @c this argument
             *              (e.g. @c Impl, @c const Impl, @c volatile Impl).
             * @tparam Pmf  The pointer-to-member-function for the target method on @p Impl.
             * @tparam R    Return type of the target method.
             * @tparam As   Parameter types of the target method.
             */
            template<typename Self, auto Pmf, typename R, typename... As>
            struct Thunk {
                static R Invoke(Self* self, As... args) { return (self->*Pmf)(static_cast<As&&>(args)...); }
            };

            /**
             * @brief Convenience wrapper instantiating @ref Thunk from a @c TypeList<As...> of params.
             */
            template<typename Self, auto Pmf, typename R, typename L>
            struct ThunkFromList;

            template<typename Self, auto Pmf, typename R, typename... As>
            struct ThunkFromList<Self, Pmf, R, Sora::Traits::TypeList<As...>> {
                using Type = Thunk<Self, Pmf, R, As...>;
            };

            /**
             * @brief The cv-qualified @p Impl reference type expected by the thunk for member @p ifaceMember.
             */
            template<typename Impl, std::meta::info ifaceMember>
            using SelfTypeFor = typename [:Detail::ThisPointerType(^^Impl, ifaceMember):];

            /**
             * @brief Build a @c TypeList<...> reflection from the parameter types of function @p f.
             */
            consteval std::meta::info ParamTypeListInfo(std::meta::info f) {
                return std::meta::substitute(^^Sora::Traits::TypeList, Meta::ParamTypesOf(f));
            }

            /**
             * @brief Reflected, declaration-ordered list of @p Vtable's synthesised slots.
             *        Available only after @ref Vtable's @c consteval{} block has completed
             *        @c define_aggregate, which is guaranteed at every use-site of @ref BuildVtable.
             */
            template<typename Iface, typename Impl>
            inline constexpr auto kVtableSlots = std::define_static_array(
                std::meta::nonstatic_data_members_of(^^Vtable<Iface, Impl>, std::meta::access_context::unchecked()));

            /**
             * @brief Find the selected Iface member matching the slot's identifier.
             *        Throws a compile-time diagnostic naming the offending slot if no selected method
             *        bears that name; that condition signals a build-system inconsistency between the
             *        @ref Vtable shape and the currently-instantiated selection.
             */
            template<typename Iface>
            consteval std::meta::info FindIfaceMemberByName(std::string_view name) {
                for (auto m : kSelectedMethods<Iface>) {
                    if (Meta::IdentifierOf(m) == name) {
                        return m;
                    }
                }
                throw std::define_static_string(
                    "Polymorphism: vtable slot '" + std::string{name} + "' on interface '" +
                    std::string{Sora::Meta::DisplayStringOf(^^Iface)} +
                    "' has no matching selected interface method (slot identifier and selected-methods "
                    "set are out of sync; likely a stale Define<Iface, Impl>() call from a previous "
                    "version of the interface).");
            }

            /**
             * @brief Build a populated @ref Vtable instance whose slots are free-function thunks into Impl.
             *
             * Iterates over the @ref Vtable's own synthesised slots and, for each, looks up the matching
             * Iface method by identifier, resolves the compatible Impl method, and installs a thunk
             * pointer. Splicing @p Vtable's own member ensures the lvalue access is well-formed; the
             * Iface member is only used to reconstruct the thunk's signature, while the target Impl
             * member is materialised as a pointer-to-member-function NTTP for the thunk.
             *
             * Throws compile-time diagnostics that identify the offending (Iface, Impl, slot) tuple
             * when no compatible Impl method exists; the @ref Implements concept is the early gate,
             * but this throw is a defence-in-depth check should the concept be bypassed.
             */
            template<typename Iface, typename Impl>
            consteval Vtable<Iface, Impl> BuildVtable() {
                Vtable<Iface, Impl> v{};
                template for (constexpr auto slot : kVtableSlots<Iface, Impl>) {
                    constexpr auto ifaceMember = FindIfaceMemberByName<Iface>(Meta::IdentifierOf(slot));
                    constexpr auto target = FindCompatible(^^Impl, ifaceMember);
                    if constexpr (target == std::meta::info{}) {
                        throw std::define_static_string(std::format(
                            "Polymorphism::BuildVtable: implementation '{}' has no method matching "
                            "interface slot '{}' on '{}'; required signature is '{}'. Add a matching method "
                            "(same identifier, parameter types, cv-qualifiers, and return type) to the "
                            "implementation, or skip the interface method with [[=Skip{{}}]].",
                            Sora::Meta::DisplayStringOf(^^Impl), Meta::IdentifierOf(ifaceMember),
                            Sora::Meta::DisplayStringOf(^^Iface),
                            Sora::Meta::DisplayStringOf(std::meta::type_of(ifaceMember))));
                    }
                    using SelfRaw = typename [:std::meta::remove_pointer(ThisPointerType(^^Impl, ifaceMember)):];
                    using R = typename [:std::meta::return_type_of(ifaceMember):];
                    using Params = typename [:ParamTypeListInfo(ifaceMember):];
                    constexpr auto pmf = &[:target:];
                    using ThunkT = typename ThunkFromList<SelfRaw, pmf, R, Params>::Type;
                    v.[:slot:] = &ThunkT::Invoke;
                }
                return v;
            }

        } // namespace Detail
        /** @endcond */

        /**
         * @brief Compile-time vtable instance for the (Iface, Impl) pair.
         *
         * Each slot is a non-capturing generic lambda specialised to forward to the corresponding @p Impl
         * method, decayed to a free function pointer of type @c R(*)(cv Impl*,Args...). The instance has
         * static storage duration and @c inline constexpr linkage; calling through it costs one indirect
         * call, fully inlinable when the optimiser sees the call site.
         */
        template<typename Iface, typename Impl>
            requires Implements<Impl, Iface>
        inline constexpr Vtable<Iface, Impl> kVtable = Detail::BuildVtable<Iface, Impl>();

        /**
         * @brief Inheritance-free runtime polymorphism handle: a fat pointer @c {Impl* target}
         *        paired with the synthesised @ref kVtable.
         *
         * Two-pointer reference: the implementation object plus the vtable for its (Iface, Impl) pair.
         * Equivalent in cost to a classical @c Iface* virtual dispatch, but the implementor never
         * inherits from @p Iface. Adapters are trivially copyable and structural.
         *
         * @tparam Iface The interface to project the implementation onto.
         * @tparam Impl  The unrelated class type providing matching methods.
         *
         * @code{.cpp}
         * struct IDrawable {
         *     virtual void Draw() = 0;
         *     virtual int  Width() const = 0;
         * };
         * struct Square {              // No inheritance!
         *     int side;
         *     void Draw();
         *     int  Width() const { return side; }
         * };
         * Square s{42};
         * Adaptor<IDrawable, Square> a{&s};
         * a.vtable().Draw(a.target);              // forwards to s.Draw()
         * int w = a.vtable().Width(a.target);     // 42
         * @endcode
         */
        template<typename Iface, typename Impl>
            requires Implements<Impl, Iface>
        struct Adaptor {
            /** @brief The bound implementation object. */
            Impl* target = nullptr;

            /**
             * @brief Reference to the compile-time vtable instance for this (Iface, Impl) pair.
             */
            [[nodiscard]] constexpr const Vtable<Iface, Impl>& vtable() const noexcept { return kVtable<Iface, Impl>; }
        };

    } // namespace Polymorphism

    namespace Concept {

        /**
         * @brief Concept alias indicating whether @p Impl satisfies interface @p Iface.
         * @tparam Iface Interface contract type.
         * @tparam Impl  Concrete implementation type.
         */
        template<typename Iface, typename Impl>
        concept CanImplementInterface = Polymorphism::Implements<Impl, Iface>;

    } // namespace Concept

    namespace Traits {

        /**
         * @brief Public alias to the polymorphism vtable instance variable template.
         */
        template<typename Iface, typename Impl>
        inline constexpr auto kVTable = Polymorphism::kVtable<Iface, Impl>;

        /**
         * @brief Compile-time ABI digest for an interface.
         * @tparam Iface Interface contract type.
         */
        template<typename Iface, bool ConsiderName = false>
        inline constexpr uint128_t AbiDigestOf =
            [] consteval { return Polymorphism::AbiDigest<Iface, ConsiderName>(); }();

    } // namespace Traits

} // namespace Sora
