/**
 * @file Polymorphism.h
 * @brief Inheritance-free, reflection-driven runtime polymorphism.
 *
 * Provides a "structural duck-type adapter": given an interface type @p Iface (a class declaring
 * virtual member functions) and an unrelated implementation type @p Impl whose members satisfy those
 * signatures structurally, synthesises at compile time a flat function-pointer vtable @ref Vtable
 * that dispatches into @p Impl, with **no inheritance relationship** between @p Iface and @p Impl.
 *
 * The vtable layout is generated by `std::meta::define_aggregate` driven by a P2996 reflection scan
 * of @p Iface; each thunk is a non-capturing generic lambda that forwards to the matching method on
 * @p Impl. The resulting cost model is:
 *   - One indirect call per dispatch (identical to a classical virtual call).
 *   - Two pointers per @ref Adapter (one for the target object, one for the vtable).
 *   - Zero per-instance allocation, zero type-erasure boxing.
 *   - Inlinable thunks: the optimiser sees through the lambda into the target method.
 *
 * The result is the runtime cost of `virtual` without forcing the implementor to inherit from
 * anything — useful for plug-in registration, ABI-stable wrappers around third-party types, gradual
 * refactoring of static-dispatch hierarchies, and concept-style interfaces with runtime polymorphism.
 *
 * @par Method selection
 * Methods on @p Iface participate in the vtable when they are non-static, non-special member
 * functions (constructors and destructors are always excluded). The selection is steered by two
 * annotation tags from @ref Anno:
 *   - `[[=Anno::Skip{}]]`  excludes an otherwise eligible method.
 *   - `[[=Anno::Force{}]]` includes a non-virtual method that would otherwise be skipped.
 * Pure-virtual methods are always selected unless `Skip`-tagged.
 *
 * @par Signature compatibility
 * For a selected Iface method `R Foo(P...) cv`, the matching Impl method must have:
 *   - identical identifier,
 *   - identical parameter types (in order),
 *   - identical cv-qualification on the implicit object parameter,
 *   - identical return type.
 * Reference-qualifiers (`&`, `&&`) on the source method have no free-function counterpart and are
 * dropped from the synthesised thunk; users should avoid them on Iface methods. Default arguments
 * on Iface methods are not propagated through the thunk (function pointers do not carry them).
 *
 * @ingroup Core
 */
#pragma once

